-- Migration 013 — Dedicated landing pages for the 20 Industries
-- Run this via admin/run-migrations.php (recommended) or paste into
-- phpMyAdmin if you prefer to apply it manually.
--
-- All twenty share one template file (templates/industry-body.php), which
-- reads the industry's copy from includes/industries.php based on the
-- page's own slug. Meta title/description are editable from Admin → Pages
-- like Home and About Us.

INSERT IGNORE INTO pages (name, slug, meta_title, meta_description, template) VALUES
('Industry — Construction & Real Estate', '/industry-construction',
  'Construction & Real Estate ERP Solution | Drawlead',
  'Run multi-site construction and real estate operations from a single system — instead of a different spreadsheet for every project.',
  'industry'),
('Industry — Healthcare & Wellness', '/industry-healthcare',
  'Healthcare & Wellness ERP Solution | Drawlead',
  'Run clinics and wellness centers where scheduling, billing, and patient follow-ups never depend on a phone call.',
  'industry'),
('Industry — Manufacturing', '/industry-manufacturing',
  'Manufacturing ERP Solution | Drawlead',
  'Track production runs, raw material stock, and quality checks from a single dashboard instead of a factory floor full of paper logs.',
  'industry'),
('Industry — Marketing Agencies', '/industry-agencies',
  'Marketing Agencies ERP Solution | Drawlead',
  'Run an agency where client projects, leads, and delivery timelines all live in one place instead of six different tools.',
  'industry'),
('Industry — Retail & E-Commerce', '/industry-retail',
  'Retail & E-Commerce ERP Solution | Drawlead',
  'Sell across stores and online channels with stock, orders, and customers synced in real time — not reconciled at the end of the day.',
  'industry'),
('Industry — Logistics & Transport', '/industry-logistics',
  'Logistics & Transport ERP Solution | Drawlead',
  'Track fleet, deliveries, and compliance documents from one dashboard instead of a driver group chat and a filing cabinet.',
  'industry'),
('Industry — Jewellery & Gems', '/industry-jewellery',
  'Jewellery & Gems ERP Solution | Drawlead',
  'Run a jewellery business where stock, purity, and billing are never a guessing game — synced across every counter and branch.',
  'industry'),
('Industry — Education & Training', '/industry-education',
  'Education & Training ERP Solution | Drawlead',
  'From admissions to fee collection to attendance, manage every part of running a school or training institute in one system.',
  'industry'),
('Industry — Hospitality & Restaurants', '/industry-hospitality',
  'Hospitality & Restaurants ERP Solution | Drawlead',
  'Manage orders, table turnover, and kitchen inventory from one dashboard instead of a POS, a notebook, and a supplier call sheet.',
  'industry'),
('Industry — Automotive & Auto Services', '/industry-automotive',
  'Automotive & Auto Services ERP Solution | Drawlead',
  'Run a dealership or service center where job cards, spare parts, and billing all live in one place — not three.',
  'industry'),
('Industry — Textile & Apparel', '/industry-textile',
  'Textile & Apparel ERP Solution | Drawlead',
  'Track raw material, production stages, and finished goods stock across every unit and showroom without a separate spreadsheet for each.',
  'industry'),
('Industry — Pharmaceuticals & Distribution', '/industry-pharma',
  'Pharmaceuticals & Distribution ERP Solution | Drawlead',
  'Manage batch tracking, expiry alerts, and regulatory compliance across your entire distribution network from one system.',
  'industry'),
('Industry — Professional Services', '/industry-professional',
  'Professional Services ERP Solution | Drawlead',
  'Run a law firm, accounting practice, or consultancy where client work, billing, and deadlines are never scattered across inboxes.',
  'industry'),
('Industry — Food & Beverage Manufacturing', '/industry-food-beverage',
  'Food & Beverage Manufacturing ERP Solution | Drawlead',
  'Track raw ingredients, batch production, and quality checks across every shift, with full traceability from ingredient to finished product.',
  'industry'),
('Industry — IT & Software Services', '/industry-it-software',
  'IT & Software Services ERP Solution | Drawlead',
  'Run a software or IT services company where project timelines, resource allocation, and client billing all live in one connected system.',
  'industry'),
('Industry — Financial Services & NBFCs', '/industry-financial',
  'Financial Services & NBFCs ERP Solution | Drawlead',
  'Manage loan accounts, repayment tracking, and regulatory compliance from one system built for how NBFCs and financial services actually operate.',
  'industry'),
('Industry — Agriculture & Agri-Business', '/industry-agriculture',
  'Agriculture & Agri-Business ERP Solution | Drawlead',
  'Track procurement, storage, and distribution of agricultural produce across every warehouse and season without losing visibility between harvests.',
  'industry'),
('Industry — Event Management', '/industry-events',
  'Event Management ERP Solution | Drawlead',
  'Run an event management business where bookings, vendor coordination, and budgets are tracked in one place, not across a dozen chat threads.',
  'industry'),
('Industry — Beauty & Salon Chains', '/industry-beauty',
  'Beauty & Salon Chains ERP Solution | Drawlead',
  'Manage appointments, staff schedules, and product inventory across every branch of your salon or spa chain from one dashboard.',
  'industry'),
('Industry — Wholesale & Distribution', '/industry-wholesale',
  'Wholesale & Distribution ERP Solution | Drawlead',
  'Manage dealer orders, stock allocation, and distribution logistics from one system instead of juggling order books and phone calls.',
  'industry');
